---
kind: Service
apiVersion: v1
metadata:
  name: es-dt-ds
  namespace: elk
  labels:
    app: elasticsearch
    role: data
spec:
  selector:
    app: elasticsearch
    role: data
  clusterIP: None
  ports:
    - name: inter-node
      port: 9300

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: es-data
  namespace: elk
spec:
  serviceName: es-dt-ds
  replicas: 2
  selector:
    matchLabels:
      app: elasticsearch
      role: data
      
  template:
    metadata:
      labels:
        app: elasticsearch
        role: data
    spec:
      volumes:
      - name: data
        emptyDir: {}
      initContainers:
      - name: increase-vm-max-map
        image: busybox
        command: ["sysctl", "-w", "vm.max_map_count=262144"]
        securityContext:
          privileged: true

      - name: fix-permissions
        image: busybox
        command: ["sh", "-c", "chown -R 1000:1000 /usr/share/elasticsearch/data"]
        securityContext:
          privileged: true
        volumeMounts:
        - name: data
          mountPath: /usr/share/elasticsearch/data

      - name: increase-fd-ulimit
        image: busybox
        command: ["sh", "-c", "ulimit -n 65536"]
        securityContext:
          privileged: true
   
      containers:
      - name: elasticsearch
        image: docker.elastic.co/elasticsearch/elasticsearch:7.2.0
        resources:
            limits:
              cpu: 1
            requests:
              cpu: 1
        ports:
        - name: inter-node
          containerPort: 9300
          protocol: TCP
        volumeMounts:
          - name: data
            mountPath: /usr/share/elasticsearch/data
        env:
          - name: cluster.name
            value: elasticsearch-cluster
          - name: node.name
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: discovery.seed_hosts
            value: "es-master-0.es-ms-ds,es-master-1.es-ms-ds,es-master-2.es-ms-ds"
          - name: cluster.initial_master_nodes
            value: "es-master-0,es-master-1,es-master-2"
          - name: ES_JAVA_OPTS
            value: "-Xms512m -Xmx512m"
          - name: node.master
            value: "false"
          - name: node.ingest
            value: "false"
          - name: node.data
            value: "true"
          - name: node.ml
            value: "true"


