---

## This role install all prerequisites to build pp-punch repository. 

- name: ensure setups directory exists
  file: path={{item}} state=directory recurse=no
  become: true
  loop:
    - "{{pp_remote_data_dir}}"

- name: ensure mandatory packages are installed
  apt:
    pkg:
    - wget
    - curl
    - unzip
    - zip
    - git
    - pandoc
  become: true

- name: Install Pyenv
  include_tasks: pyenv.yml

- name: Install Openjdk
  include_tasks: open-jdk.yml

- name: Install maven
  include_tasks: maven.yml

- name: Install pp-integration dependencies
  include_tasks: integration.yml

