## Maven installation 

- name: download maven
  get_url: dest={{pp_remote_data_dir}} url={{maven_source_url}} mode=555
  become: true

- name: unarchive maven 
  unarchive:
    src: /tmp/{{maven_version}}-bin.tar.gz
    dest: "{{pp_remote_data_dir}}"
    remote_src: yes 

- name: Create symbolic link 
  file:
    src: "{{pp_remote_data_dir}}/{{maven_version}}"
    dest: "{{pp_remote_data_dir}}/maven" 
    state: link
  
- name: Check that the maven.sh exists
  stat:
    path: /etc/profile.d/maven.sh
  register: stat_result

- name: manage env var for maven 
  lineinfile:
    path: /etc/profile.d/maven.sh
    line: "{{ item }}"
    create: yes
  loop:
    - export M2_HOME={{pp_remote_data_dir}}/maven
    - export MAVEN_HOME={{pp_remote_data_dir}}/maven
    - export PATH=${M2_HOME}/bin:${PATH}
  become: true
  when: not stat_result.stat.exists

- name: Source the maven file
  shell: source /etc/profile.d/maven.sh
  args:
     executable: /bin/bash