# Dependencies for pp-integration

- name: Install python dependencies 
  pip:
    name: 
      - pex==2.1.4
      - Jinja2==2.10.3
      - PyYAML==5.3.1

- name: Install jq
  apt:
    pkg:
    - jq
  become: true