
apiVersion: v1
kind: Service
metadata:
  name: mlflow-rest-svc
  labels:
    app: mlflow
    type: rest
    version: "1.0"

spec:
  selector:
    app: mlflow-rest
  type: NodePort
  ports:
  - name: api
    port: 6060
    targetPort: 6060
    nodePort: 31000


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name:  mlflow-rest
  labels:
    app: mlflow
    type: rest
    version: "1.0"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mlflow-rest
      version: "1.0"
  template:
    metadata:
      labels:
        app: mlflow-rest
        version: "1.0"
    spec:
      imagePullSecrets:
      - name: registry-secret
      containers:
      - name: rest
        image: jumsdu92/images:kmeans-api
       
        resources:
          limits:
            cpu: 1
        ports:
        - containerPort: 6060
          name: http


