---
# tasks to setup a punchplatform targets for Ubuntu18 only


- name: Ensure targets dependencies for python packages are installed
  apt: name={{item}}
  become: yes
  loop:
       - python3-pip
       - python3-venv

- name: Create a symbolic link between python & python3
  file:
    src: /usr/bin/python3
    dest: /usr/bin/python
    state: link
  become: true
  when: ansible_distribution=='Ubuntu' and ansible_distribution_version=='18.04'
