---
# Tasks for setting up a local docker-based kubernetes, based on 'kind'

# Following https://kind.sigs.k8s.io/docs/user/quick-start/
 # and deploymentPBRB.md

- name: ensure setups and docker data directory exists
  file: path={{item}} state=directory recurse=no
  become: true
  loop:
    - "{{pp_remote_data_dir}}"
    - "{{pp_remote_setups_dir}}"
    - "{{docker_data_dir}}"
    - "{{kind_setup_dir}}"




- name: ensure docker uses appropriate data dir
  file: path=/var/lib/docker state=link src={{docker_data_dir}} force=true
  become: true

- name: ensure docker package is installed
  apt: name=docker.io
  become: true

- name: download Kind tool
  get_url: dest={{kind_exe}} url={{kind_source_url}} mode=555
  become: true

- name: ensure operator is member of docker group
  user: name={{pp_kube_operator}} home={{user_home}} shell=/bin/bash groups=docker update_password=on_create append=true
  become: true

- name: ensure operator path includes Kind tool
  lineinfile: 
    dest: "{{user_home}}/.bashrc"
    line: "export PATH={{kind_setup_dir}}:$PATH"
    regexp: "export PATH=.*kind:"

- name: ensure kubectl is installed
  snap: name=kubectl classic=yes
  become: true

- name: check if kube cluster exists
  shell: "{{kind_exe}} get clusters | grep kube"
  become: true{{kind_exe}}
  become_user: "{{pp_kube_operator}}"
  register: kube_cluster_check
  failed_when: false
  changed_when: not ( 'kube' in kube_cluster_check.stdout )

- name: create kube cluster if it does not exist
  become: true
  become_user: "{{pp_kube_operator}}"
  shell: "{{kind_exe}} create cluster --name kube --retain"
  when: kube_cluster_check.changed
  
