apiVersion: v1
kind: Service
metadata:
  name: kibana-svc
  namespace: elk
  labels:
    app: kibana
spec:
  selector:
    app: kibana
  type: NodePort
  #if you deploy in cloud
  #type: LoadBalancer
  ports:
  - name: http
    port: 5601
    targetPort: 5601
    protocol: TCP
    nodePort: 31000


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kibana
  namespace: elk
  labels:
    app: kibana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kibana
  template:
    metadata:
      labels:
        app: kibana
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - kibana
            topologyKey: "kubernetes.io/hostname"
      containers:
      - name: es-kibana
        image: docker.elastic.co/kibana/kibana:7.6.2
        env:
        - name: ELASTICSEARCH_HOSTS
          value: http://es-svc.elk:9200
        resources:
          limits:
            cpu: 0.5
        ports:
        - containerPort: 5601
          name: http


