apiVersion: v1
kind: Namespace
metadata:
  name: elk

---
kind: Service
apiVersion: v1
metadata:
  name: es-svc
  namespace: elk
  labels:
    app: elasticsearch
    role: all
spec:
  selector:
    app: elasticsearch
    role: all
  ports:
  - name: inter-node
    port: 9300
  - name: rest
    port: 9200
        
    
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: es-cluster
  namespace: elk
spec:
  serviceName: es-svc
  replicas: 4
  selector:
    matchLabels:
      app: elasticsearch
      role: all
  template:
    metadata:
      labels:
        app: elasticsearch
        role: all
    spec:
        volumes:
        - name: data
          emptyDir: {}
        initContainers:
        - name: increase-vm-max-map
          image: busybox
          command: ["sysctl", "-w", "vm.max_map_count=262144"]
          securityContext:
            privileged: true

        - name: fix-permissions
          image: busybox
          command: ["sh", "-c", "chown -R 1000:1000 /usr/share/elasticsearch/data"]
          securityContext:
            privileged: true
          volumeMounts:
          - name: data
            mountPath: /usr/share/elasticsearch/data

        - name: increase-fd-ulimit
          image: busybox
          command: ["sh", "-c", "ulimit -n 65536"]
          securityContext:
           privileged: true
    
        containers:
        - name: elasticsearch
          image: docker.elastic.co/elasticsearch/elasticsearch:7.2.0
          resources:
             limits:
                 cpu: 1
             requests:
                 cpu: 1
          ports:
          - name: inter-node
            containerPort: 9300
            protocol: TCP
          - name: rest
            containerPort: 9200
            protocol: TCP

          volumeMounts:
          - name: data
            mountPath: /usr/share/elasticsearch/data
          env:
          - name: cluster.name
            value: elasticsearch-cluster-dev
          - name: node.name
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: discovery.seed_hosts
            value: "es-cluster-0.es-svc,es-cluster-1.es-svc,es-cluster-2.es-svc"
          - name: cluster.initial_master_nodes
            value: "es-cluster-0,es-cluster-1,es-cluster-2"
          - name: ES_JAVA_OPTS
            value: "-Xms512m -Xmx512m"


